apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: tls-junte-ui-com
  - hosts:
    - www.{{ .Values.domain }}
    secretName: tls-www-junte-ui-com
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 8080
  - host: www.{{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 8080

