image: node:10.9

variables:
  GIT_DEPTH: 5
  GIT_STRATEGY: fetch

stages:
  - build
  - publish

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@8.3.3
    - npm install
    - npm run build:prod
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - master

pages:
  stage: publish
  image: debian:jessie
  variables:
    GIT_STRATEGY: none
  script:
    - mkdir public
    - mv dist/junte-ui-app/* public/
  artifacts:
    paths:
      - public
  only:
    - master
