image: node:8.11.1

stages:
  - build
  - publish

build:
  stage: build
  cache:
    paths:
    - node_modules/
  script:
  - echo $NPM_TOKEN
  - npm install -g @angular/cli@7.1.0
  - npm install
  - npm run build:prod
  - npm run build
  artifacts:
    paths:
    - dist
  only:
  - master

publish_npm:
  stage: publish
  script:
  - npm run npm:pack
  - echo $NPM_TOKEN
  # - export NPM_TOKEN 
  - npm login
  - npm run publish
  only:
  - master

pages:
  stage: publish
  image: debian:jessie
  variables:
    GIT_STRATEGY: none
  script:
  # - npm install -g @angular/cli@7.1.0
  # - npm install
  # - npm run build:prod
  # - npm run build  
  - mkdir public
  - mv dist/junte-ui-app/* public/
  artifacts:
    paths:
    - public
  only:
  - master
