image: docker:18
variables:
  DOCKER_DRIVER: overlay
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID
  DOCKER_BUILD_IMAGE: $CI_REGISTRY_IMAGE:build-$CI_PIPELINE_IID
  DOCKER_CACHE_IMAGE: $CI_REGISTRY_IMAGE:cache
  GIT_STRATEGY: none

stages:
  - build
  - deploy
  - publish

build:
  stage: build
  variables:
    GIT_DEPTH: 5
    GIT_STRATEGY: fetch
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $DOCKER_CACHE_IMAGE || true
    - docker build
          --cache-from $DOCKER_CACHE_IMAGE
          --target build
          -t $DOCKER_CACHE_IMAGE
          -t $DOCKER_BUILD_IMAGE
          -f deploy/Dockerfile .
    - docker build 
             --cache-from $DOCKER_CACHE_IMAGE 
             -t $DOCKER_IMAGE 
             -f deploy/Dockerfile .
    - docker push $DOCKER_IMAGE
    - docker push $DOCKER_CACHE_IMAGE
    - docker push $DOCKER_BUILD_IMAGE

deploy:
  image: junte/helm-deploy:1.3-helm2.16.1
  stage: deploy
  dependencies: []
  variables:
    GIT_DEPTH: 5
    GIT_STRATEGY: fetch
    HELM_IMAGE_TAG: $CI_PIPELINE_IID
  script:
    - helm_deploy
  environment:
    name: production
    url: $SITE_ADDRESS
  only:
    - master

.publish:
  image: $DOCKER_BUILD_IMAGE
  stage: publish
  services:
    - docker:dind

publish_master:
  extends: .publish
  script:
    - cd /src/projects/junte-ui
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm run publish
  only:
    - master