image: node:8.11.1

stages:
  - build
  - publish

build:
  stage: build
  cache:
    paths:
    - node_modules/
  script:
  - npm install -g @angular/cli@7.1.0
  - npm install
  - npm run build:prod
  artifacts:
    paths:
    - dist/junte-ui
  only:
  - master

publish_npm:
  stage: publish
  script:
  - npm run npm:pack
  - npm login
  - npm run publish
  only:
  - master

pages:
  stage: publish
  image: debian:jessie
  variables:
    GIT_STRATEGY: none
  script:
  # - npm install -g @angular/cli@7.1.0
  # - npm install
  # - npm run build:prod
  # - npm run build
  - ls -l
  - ls -l dist
  - ls -l dist/junte-ui/
  - mv dist/junte-ui/* public/
  - mkdir public
  - cp -r dist/junte-ui/* public/
  artifacts:
    paths:
    - public
  only:
  - master
