image: node:8.11.1

variables:
  GIT_STRATEGY: none

stages:
  - build
  - publish

build:
  stage: build
  cache:
    paths:
    - node_modules/
  variables:
    GIT_DEPTH: 5
    GIT_STRATEGY: fetch
  script:
  - npm install -g @angular/cli@7.1.0
  - npm install
  - npm run build:prod
  artifacts:
    paths:
    - dist/junte-ui
  only:
  - master

publish_npm:
  stage: publish
  script:
  - npm run npm:pack
  - npm login
  - npm run publish
  only:
  - master

pages:
  image: alpine:3.9
  stage: publish
  script:
  # - npm install -g @angular/cli@7.1.0
  # - npm install
  # - npm run build:prod
  # - npm run build
  - ls -l
  - mv dist/junte-ui/* public/
  artifacts:
    paths:
    - public
  only:
  - master
