image: node:8.11.1

stages:
  - publish

publish_npm:
  stage: publish
  script:
  - npm install gulp
  - npm run package
  - npm login
  - npm run publish
  only:
  - master

pages:
  stage: publish
  cache:
    paths:
    - node_modules/
  script:
  - npm install -g @angular/cli@7.1.0
  - npm install
  - npm run build:prod
  - npm run build
  - mv dist/junte-ui-app/* public/
  artifacts:
    paths:
    - public
  only:
  - master
