image: node:8.11.1

variables:
  GIT_DEPTH: 5
  GIT_STRATEGY: fetch

stages:
  - build
  - publish

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - export $PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - echo $PACKAGE_VERSION
    - npm install -g @angular/cli@7.1.0
    - npm install
    - npm run build:prod
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - master

publish_npm:
  stage: publish
  script:
    - npm run npm:pack
    - npm set //registry.npmjs.org/:_authToken="${NPM_TOKEN}"
    - export $PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - echo $PACKAGE_VERSION
    # - npm login
    - ls -l dist/junte-ui/
    - npm publish ./dist/junte-ui/junte-ui-${PACKAGE_VERSION}.tgz
  only:
    - master

pages:
  stage: publish
  image: debian:jessie
  variables:
    GIT_STRATEGY: none
  script:
    - mkdir public
    - mv dist/junte-ui-app/* public/
  artifacts:
    paths:
      - public
  only:
    - master
