enum FontGesturesIcons {
  pointerLeft = 'pointer-left',
  pointerUp = 'pointer-up',
  pointerRight = 'pointer-right',
  pointerDown = 'pointer-down',
  hand = 'hand',
  fingerTap = 'finger-tap',
  fingersTap = 'fingers-tap',
  reminder = 'reminder',
  fingersCrossed = 'fingers-crossed',
  fingersVictory = 'fingers-victory',
  gestureZoom = 'gesture-zoom',
  gesturePinch = 'gesture-pinch',
  fingersScrollHorizontal = 'fingers-scroll-horizontal',
  fingersScrollVertical = 'fingers-scroll-vertical',
  fingersScrollLeft = 'fingers-scroll-left',
  fingersScrollRight = 'fingers-scroll-right',
  pointerLeft2 = 'pointer-left2',
  pointerUp2 = 'pointer-up2',
  pointerRight2 = 'pointer-right2',
  pointerDown2 = 'pointer-down2',
  hand2 = 'hand2',
  fingerTap2 = 'finger-tap2',
  fingersTap2 = 'fingers-tap2',
  reminder2 = 'reminder2',
  gestureZoom2 = 'gesture-zoom2',
  gesturePinch2 = 'gesture-pinch2',
  fingersScrollHorizontal2 = 'fingers-scroll-horizontal2',
  fingersScrollVertical2 = 'fingers-scroll-vertical2',
  fingersScrollLeft2 = 'fingers-scroll-left2',
  fingersScrollRight2 = 'fingers-scroll-right2',
  fingersScrollVertical3 = 'fingers-scroll-vertical3'
}

export const gesturesIcons = {
  fingersCrossed: FontGesturesIcons.fingersCrossed + ':font:junte-ui-icons-gestures',
  fingersScrollHorizontal2: FontGesturesIcons.fingersScrollHorizontal2 + ':font:junte-ui-icons-gestures',
  fingersScrollHorizontal: FontGesturesIcons.fingersScrollHorizontal + ':font:junte-ui-icons-gestures',
  fingersScrollLeft2: FontGesturesIcons.fingersScrollLeft2 + ':font:junte-ui-icons-gestures',
  fingersScrollLeft: FontGesturesIcons.fingersScrollLeft + ':font:junte-ui-icons-gestures',
  fingersScrollRight2: FontGesturesIcons.fingersScrollRight2 + ':font:junte-ui-icons-gestures',
  fingersScrollRight: FontGesturesIcons.fingersScrollRight + ':font:junte-ui-icons-gestures',
  fingersScrollVertical2: FontGesturesIcons.fingersScrollVertical2 + ':font:junte-ui-icons-gestures',
  fingersScrollVertical3: FontGesturesIcons.fingersScrollVertical3 + ':font:junte-ui-icons-gestures',
  fingersScrollVertical: FontGesturesIcons.fingersScrollVertical + ':font:junte-ui-icons-gestures',
  fingersTap2: FontGesturesIcons.fingersTap2 + ':font:junte-ui-icons-gestures',
  fingersTap: FontGesturesIcons.fingersTap + ':font:junte-ui-icons-gestures',
  fingersVictory: FontGesturesIcons.fingersVictory + ':font:junte-ui-icons-gestures',
  fingerTap2: FontGesturesIcons.fingerTap2 + ':font:junte-ui-icons-gestures',
  fingerTap: FontGesturesIcons.fingerTap + ':font:junte-ui-icons-gestures',
  pointerDown2: FontGesturesIcons.pointerDown2 + ':font:junte-ui-icons-gestures',
  pointerDown: FontGesturesIcons.pointerDown + ':font:junte-ui-icons-gestures',
  pointerLeft2: FontGesturesIcons.pointerLeft2 + ':font:junte-ui-icons-gestures',
  pointerLeft: FontGesturesIcons.pointerLeft + ':font:junte-ui-icons-gestures',
  pointerRight2: FontGesturesIcons.pointerRight2 + ':font:junte-ui-icons-gestures',
  pointerRight: FontGesturesIcons.pointerRight + ':font:junte-ui-icons-gestures',
  pointerUp2: FontGesturesIcons.pointerUp2 + ':font:junte-ui-icons-gestures',
  pointerUp: FontGesturesIcons.pointerUp + ':font:junte-ui-icons-gestures',
  reminder2: FontGesturesIcons.reminder2 + ':font:junte-ui-icons-gestures',
  reminder: FontGesturesIcons.reminder + ':font:junte-ui-icons-gestures',
  gesturePinch2: FontGesturesIcons.gesturePinch2 + ':font:junte-ui-icons-gestures',
  gesturePinch: FontGesturesIcons.gesturePinch + ':font:junte-ui-icons-gestures',
  gestureZoom2: FontGesturesIcons.gestureZoom2 + ':font:junte-ui-icons-gestures',
  gestureZoom: FontGesturesIcons.gestureZoom + ':font:junte-ui-icons-gestures',
  hand2: FontGesturesIcons.hand2 + ':font:junte-ui-icons-gestures',
  hand: FontGesturesIcons.hand + ':font:junte-ui-icons-gestures',
};
