import { animated } from './animated';
import { emoji } from './emoji';
import { flags } from './flags';
import { gestures } from './gestures';

export enum FontIcons {
  plus = 'plus',
  minus = 'minus',
  close = 'close',
  check = 'check',
  burger = 'menu',
  add = 'add',
  cancel = 'cancel',
  reload = 'reload',
  actions = 'actions',
  arrowLeft = 'arrow-left',
  arrowRight = 'arrow-right',
  arrowUp = 'arrow-up',
  arrowDown = 'arrow-down',
  chevronLeft = 'chevron-left',
  chevronRight = 'chevron-right',
  chevronUp = 'chevron-up',
  chevronDown = 'chevron-down',
  arrowFirst = 'arrow-first',
  arrowLast = 'arrow-last',
  chevronDoubleLeft = 'chevron-double-left',
  chevronDoubleRight = 'chevron-double-right',
  expand = 'expand',
  sortDown = 'sort-down',
  sorting = 'sorting',
  home = 'home',
  clover = 'clover',
  tree = 'tree',
  share = 'share',
  sync = 'sync',
  externalLink = 'external-link',
  download = 'download',
  cloud = 'cloud',
  save = 'save',
  delete = 'delete',
  edit = 'edit',
  file = 'file',
  copy = 'copy',
  cut = 'cut',
  mail = 'mail',
  printer = 'printer',
  picture = 'picture',
  camera = 'camera',
  user = 'user',
  addUser = 'add-user',
  delUser = 'del-user',
  team = 'team',
  addTeam = 'add-team',
  delTeam = 'del-team',
  contacts = 'contacts',
  profile = 'profile',
  view = 'view',
  search = 'search',
  dashboard = 'dashboard',
  power = 'power',
  settings = 'settings',
  warning = 'warning',
  information = 'information',
  question = 'question',
  stopping = 'stopping',
  project = 'project',
  money = 'money',
  like = 'like',
  dislike = 'dislike',
  bubble = 'bubble',
  tag = 'tag',
  bell = 'bell',
  filter = 'filter',
  map = 'map',
  compass = 'compass',
  pin = 'pin',
  finish = 'finish',
  solar = 'solar',
  moon = 'moon',
  accessLock = 'access-lock',
  accessUnlock = 'access-unlock',
  layout = 'layout',
  forms = 'forms',
  webProgramming = 'web-programming',
  elements = 'elements',
  graphic = 'graphic',
  time = 'time',
  calendar = 'calendar',
  grid = 'grid',
  creditCard = 'credit-card',
  run = 'run',
  send = 'send',
  poop = 'poop',
  collections = 'collections',
  more = 'more',
  overlays = 'overlays',
  charts = 'charts',
  crown = 'crown',
  direction = 'direction',
  beaker = 'beaker',
  mailbox = 'mailbox',
  email = 'email',
  cup = 'cup',
  move = 'move',
  pause = 'pause',
  bug = 'bug',
  anchor = 'anchor'
}

export const icons = {
  accessLock: FontIcons.accessLock + ':font',
  accessUnlock: FontIcons.accessUnlock + ':font',
  actions: FontIcons.actions + ':font',
  add: FontIcons.add + ':font',
  addGroup: FontIcons.addTeam + ':font',
  addUser: FontIcons.addUser + ':font',
  anchor: FontIcons.anchor + ':font',
  arrowDown: FontIcons.arrowDown + ':font',
  arrowFirst: FontIcons.arrowFirst + ':font',
  arrowLast: FontIcons.arrowLast + ':font',
  arrowLeft: FontIcons.arrowLeft + ':font',
  arrowRight: FontIcons.arrowRight + ':font',
  arrowUp: FontIcons.arrowUp + ':font',
  beaker: FontIcons.beaker + ':font',
  bell: FontIcons.bell + ':font',
  burger: FontIcons.burger + ':font',
  calendar: FontIcons.calendar + ':font',
  cancel: FontIcons.cancel + ':font',
  charts: FontIcons.charts + ':font',
  chat: FontIcons.bubble + ':font',
  check: FontIcons.check + ':font',
  chevronDoubleLeft: FontIcons.chevronDoubleLeft + ':font',
  chevronDoubleRight: FontIcons.chevronDoubleRight + ':font',
  chevronDown: FontIcons.chevronDown + ':font',
  chevronLeft: FontIcons.chevronLeft + ':font',
  chevronRight: FontIcons.chevronRight + ':font',
  chevronUp: FontIcons.chevronUp + ':font',
  close: FontIcons.close + ':font',
  cloudComputing: FontIcons.cloud + ':font',
  clover: FontIcons.clover + ':font',
  collections: FontIcons.collections + ':font',
  compass: FontIcons.compass + ':font',
  contacts: FontIcons.contacts + ':font',
  copy: FontIcons.copy + ':font',
  creditCard: FontIcons.creditCard + ':font',
  crown: FontIcons.crown + ':font',
  cup: FontIcons.cup + ':font',
  dashboard: FontIcons.dashboard + ':font',
  delete: FontIcons.delete + ':font',
  delGroup: FontIcons.delTeam + ':font',
  delUser: FontIcons.delUser + ':font',
  direction: FontIcons.direction + ':font',
  dislike: FontIcons.dislike + ':font',
  download: FontIcons.download + ':font',
  edit: FontIcons.edit + ':font',
  elements: FontIcons.elements + ':font',
  email: FontIcons.email + ':font',
  expand: FontIcons.expand + ':font',
  externalLink: FontIcons.externalLink + ':font',
  file: FontIcons.file + ':font',
  filter: FontIcons.filter + ':font',
  finish: FontIcons.finish + ':font',
  forms: FontIcons.forms + ':font',
  graphic: FontIcons.graphic + ':font',
  grid: FontIcons.grid + ':font',
  home: FontIcons.home + ':font',
  information: FontIcons.information + ':font',
  layout: FontIcons.layout + ':font',
  like: FontIcons.like + ':font',
  mail: FontIcons.mail + ':font',
  mailbox: FontIcons.mailbox + ':font',
  map: FontIcons.map + ':font',
  minus: FontIcons.minus + ':font',
  money: FontIcons.money + ':font',
  moon: FontIcons.moon + ':font',
  more: FontIcons.more + ':font',
  move: FontIcons.move + ':font',
  overlays: FontIcons.overlays + ':font',
  photoCamera: FontIcons.camera + ':font',
  picture: FontIcons.picture + ':font',
  pin: FontIcons.pin + ':font',
  plus: FontIcons.plus + ':font',
  poop: FontIcons.poop + ':font',
  power: FontIcons.power + ':font',
  printer: FontIcons.printer + ':font',
  profile: FontIcons.profile + ':font',
  project: FontIcons.project + ':font',
  question: FontIcons.question + ':font',
  reload: FontIcons.reload + ':font',
  save: FontIcons.save + ':font',
  search: FontIcons.search + ':font',
  settings: FontIcons.settings + ':font',
  share: FontIcons.share + ':font',
  solar: FontIcons.solar + ':font',
  sortDown: FontIcons.sortDown + ':font',
  sorting: FontIcons.sorting + ':font',
  stopping: FontIcons.stopping + ':font',
  sync: FontIcons.sync + ':font',
  tag: FontIcons.tag + ':font',
  team: FontIcons.team + ':font',
  time: FontIcons.time + ':font',
  tree: FontIcons.tree + ':font',
  user: FontIcons.user + ':font',
  view: FontIcons.view + ':font',
  warning: FontIcons.warning + ':font',
  pause: FontIcons.pause + ':font',
  bug: FontIcons.bug + ':font',
  webProgramming: FontIcons.webProgramming + ':font',

  angular: 'angular:svg:default',
  gitlab: 'gitlab:svg:default',
  arnold: 'arnold:svg:default',
  dribbble: 'dribbble:svg:default',
  github: 'github:svg:default',
  figma: 'figma:svg:default',

  gestures: gestures,
  flags: flags,
  emoji: emoji,
  animated: animated
};
