import { animated } from './animated';
import { emoji } from './emoji';
import { flags } from './flags';
import { gestures } from './gestures';

export

 const icons = {
  font: {
    access: {
      lock: 'access-lock:font',
      unlock: 'access-unlock:font'
    },
    actions: {
      actions: 'actions:font',
      file: 'file:font',
      add: 'add:font',
      edit: 'edit:font',
      save: 'save:font',
      copy: 'copy:font',
      cut: 'cut:font',
      search: 'search:font',
      printer: 'printer:font',
      plus: 'plus:font',
      minus: 'minus:font',
      close: 'close:font',
      cancel: 'cancel:font',
      delete: 'delete:font',
      reload: 'reload:font',
      power: 'power:font',
      settings: 'settings:font',
      burger: 'menu:font',
      expand: 'expand:font',
      move: 'move:font',
    },
    information: {
      information: 'information:font',
      question: 'question:font',
      warning: 'warning:font',
      stop: 'stopping:font',
      time: 'time:font',
      home: 'home:font',
    },
    media: {
      image: 'picture:font',
      pause: 'pause:font',
      send: 'send:font',
    },
    internet: {
      poop: 'poop:font',
      dashboard: 'dashboard:font',
      download: 'download:font',
      could: 'cloud:font',
      sync: 'sync:font',
      sorting: 'sorting:font',
      view: 'view:font',
      link: 'external-link:font',
      email: 'email:font',
      mail: 'mail:font',
      bubble: 'bubble:font',
    },
    programming: {
      programming: 'web-programming:font',
      bug: 'bug:font',
    },
    social: {
      like: 'like:font',
      dislike: 'dislike:font',
      profile: 'profile:font',
      bell: 'bell:font',
      team: 'team:font',
      user: 'user:font',
      addUser: 'add-user:font',
      delUser: 'del-user:font',
      addTeam: 'add-team:font',
      delTeam: 'del-team:font',
    },
    chevron: {
      doubleLeft: 'chevron-double-left:font',
      doubleRight: 'chevron-double-right:font',
      down: 'chevron-down:font',
      left: 'chevron-left:font',
      right: 'chevron-right:font',
      up: 'chevron-up:font',
    },
    arrow: {
      down: 'arrow-down:font',
      first: 'arrow-first:font',
      last: 'arrow-last:font',
      left: 'arrow-left:font',
      right: 'arrow-right:font',
      up: 'arrow-up:font',
    },
    anchor: 'anchor:font',
    cup: 'cup:font',
    run: 'run:font',
    creditCard: 'credit-card:font',
    calendar: 'calendar:font',
    pin: 'pin:font',
    compass: 'compass:font',
    map: 'map:font',
    filter: 'filter:font',
    money: 'money:font',
    project: 'project:font',
    camera: 'camera:font',
    check: 'check:font',
    solar: 'solar:font',
    moon: 'moon:font',
    emoji: {
      evil: 'evil:font',
      laughter: 'laughter:font',
      sad: 'sad:font',
      shocked: 'shocked:font',
      skull: 'skull:font',
      smile: 'smile:font',
      wink: 'wink:font',
      neutral: 'neutral:font'
    },
    gestures: {
      scrollVertical: 'fingers-scroll-vertical:font',
      scrollVertical2: 'fingers-scroll-vertical2:font',
      scrollVertical3: 'fingers-scroll-vertical3:font',
      doubleTab: 'fingers-tab:font',
      doubleTab2: 'fingers-tab2:font',
      victory: 'fingers-victory:font',
      right: 'fingers-right:font',
      right2: 'fingers-right2:font',
      up: 'fingers-up:font',
      up2: 'fingers-up2:font',
      reminder: 'reminder:font',
      reminder2: 'reminder2:font',
      tab: 'finger-tab:font',
      tab2: 'finger-tab2:font',
      crossed: 'finger-crossed:font',
      scrollHorizontal: 'fingers-scroll-horizontal:font',
      scrollHorizontal2: 'fingers-scroll-horizontal2:font',
      scrollLeft: 'fingers-scroll-left:font',
      scrollLeft2: 'fingers-scroll-left2:font',
      scrollRight: 'fingers-scroll-right:font',
      pinch: 'gesture-pinch:font',
      pinch2: 'gesture-pinch2:font',
      zoom: 'gesture-zoom:font',
      hand: 'hand:font',
      hand2: 'hand2:font',
      down: 'pointer-down:font',
      down2: 'pointer-down2:font',
      left: 'pointer-left:font',
      left2: 'pointer-left2:font',
    },
  },
  svg: {
    flags: flags,
    apps: {
      angular: 'angular:svg:apps',
      gitlab: 'gitlab:svg:apps',
      dribbble: 'dribbble:svg:apps',
      github: 'github:svg:apps',
      figma: 'figma:svg:apps',
    }
  },
  animated: animated
};
